AllCops:
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "public/**/*"
  TargetRubyVersion: 2.4
Layout/LineLength:
  Enabled: true
  Max: 120
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'